### ISSUE TITLE
Add DB Fail Over List

### ISSUE THREAD

**Issue by kcajmagic** [Comcast/codex#62]
If the database cluster the package is talking to goes down, there should be a back up list of clusters to try.

Think of it as a primary cluster and a backup list. So if the primary cluster comes back, the active connection should go from the backup list back to the primary.

**Comment by kristinaspring** [comment]
> Think of it as a primary cluster and a backup list. So if the primary cluster comes back, the active connection should go from the backup list back to the primary.

We need a configurable interval for when to ping the primary cluster to check if it's back.  Also, I think we need an ordered list, otherwise different svalinns may fall back to different clusters, causing issues (only a problem if we are supposed to insert only to one region).

**Comment by kcajmagic** [comment]
Yes, I agree.

**Comment by kristinaspring** [comment]
Closing this as it is not needed anymore.
